mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.conf.urls import url

urlpatterns = [
    path('polls/', include('polls.urls', 'django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
]

polls/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'polls'
urlpatterns = [

    path('', views.IndexView.as_view(), name='home'),
    path('polls/', views.AllPollsView.as_view(), name='polls'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.utils import timezone
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Choice, Question
# Create your views here.


#@method_decorator(login_required, name='dispatch')
class IndexView(LoginRequiredMixin, generic.ListView):

    template_name = 'polls/home.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]



class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(LoginRequiredMixin, generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

class AllPollsView(LoginRequiredMixin, generic.ListView):
    template_name = 'polls/polls.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html',
                      {
                          'question': question,
                          'error_message': "You didn't select a choice."
                      })

    selected_choice.votes += 1
    selected_choice.save()

    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

templates/polls/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
    <div class="col-sm-8 text-left">
        <h1>{{ question.question_text }}</h1>
    </div>

    <div class="col-sm-8 text-left">
        {%  if error_message %}
            <p><strong> {{ error_message }}</strong></p>
        {% endif %}

        <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter}}"> {{ choice.choice_text }}</label><br>
            {% endfor %}
            <input type="submit" value="Vote" class="btn btn-success">
        </form>
    </div>


</body>
</html>

templates/polls/home.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

    <div class="col-sm-8 text-left" id="header">
        <ul class="nav navbar-nav">
            <h1></h1>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <p><a href="{% url 'logout' %}">logout</a>
            <a href="/admin"><span class="glyphicon glyphicon-log-in btn-lg"></span> Admin-login</a></p>
        </ul>
    </div>

    <div class="col-sm-8 text-left" id="recent_questions">
    {% if latest_question_list %}
        <table class="table">
            <thead>
                <tr>
                    <th>Question:</th>
                    <th>Published:</th>
                    <th>Answer:</th>
                    <th>Results:</th>
                </tr>
            </thead>
            <tbody>
            {% for question in latest_question_list %}
                <tr>
                    <td>{{ question.question_text }}</td>
                    <td>{{ question.pub_date }}</td>
                    <form action="{% url 'polls:detail' question.id %}">
                        <td><input type="submit" value="Answer" class="btn btn-warning btn-sm"></td>
                    </form>
                    <form action="{% url 'polls:results' question.id %}">
                        <td><input type="submit" value="Results" class="btn btn-warning btn-sm"></td>
                    </form>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    {% else %}
        <p>No polls are available.</p>
    {% endif %}

    <a href="{%  url 'polls:polls'%} ">See all polls</a>
    </div>


</body>
</html>

templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

    <div class="col-sm-8 text-left" id="header">
        <ul class="nav navbar-nav">
            <h1>Polls</h1>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <a href="/admin"><span class="glyphicon glyphicon-log-in btn-lg"></span> Admin-login</a>
        </ul>
    </div>

    <div class="col-sm-8 text-left" id="recent_questions">
    {% if latest_question_list %}
        <table class="table">
            <thead>
                <tr>
                    <th>Question:</th>
                    <th>Published:</th>
                    <th>Answer:</th>
                    <th>Results:</th>
                </tr>
            </thead>
            <tbody>
            {% for question in latest_question_list %}
                <tr>
                    <td>{{ question.question_text }}</td>
                    <td>{{ question.pub_date }}</td>
                    <form action="{% url 'polls:detail' question.id %}">
                        <td><input type="submit" value="Answer" class="btn btn-warning btn-sm"></td>
                    </form>
                    <form action="{% url 'polls:results' question.id %}">
                        <td><input type="submit" value="Results" class="btn btn-warning btn-sm"></td>
                    </form>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    {% else %}
        <p>No polls are available.</p>
    {% endif %}

    <a href="{%  url 'polls:polls'%} ">See all polls</a>
    </div>


</body>
</html>

templates/polls/polls.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
 <div class="col-sm-8 text-left" id="header">
        <ul class="nav navbar-nav">
            <h1>All Polls</h1>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <p><a href="{% url 'logout' %}">logout</a>
            <a href="/admin"><span class="glyphicon glyphicon-log-in btn-lg"></span> Admin-login</a></p>
        </ul>
    </div>

    <div class="col-sm-8 text-left" id="recent_questions">
    {% if question_list %}
        <table class="table">
            <thead>
                <tr>
                    <th>Question:</th>
                    <th>Published:</th>
                    <th>Answer:</th>
                    <th>Results:</th>
                </tr>
            </thead>
            <tbody>
            {% for question in question_list %}
                <tr>
                    <td>{{ question.question_text }}</td>
                    <td>{{ question.pub_date }}</td>
                    <form action="{% url 'polls:detail' question.id %}">
                        <td><input type="submit" value="Answer" class="btn btn-warning btn-sm"></td>
                    </form>
                    <form action="{% url 'polls:results' question.id %}">
                        <td><input type="submit" value="Results" class="btn btn-warning btn-sm"></td>
                    </form>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    {% else %}
        <p>No polls are available.</p>
    {% endif %}
    </div>


</body>
</html>

templates/polls/results.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Results</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>


    <h1>{{ question.question_text }}</h1>


    <table class="table" id="choice_table">
    <thead>
      <tr>
        <th>Choice:</th>
        <th>Votes:</th>
        {% for choice in question.choice_set.all %}
            <tr>
                <td>{{ choice.choice_text }}</td>
                <td>{{ choice.votes }} vote{{ choice.votes|pluralize }}</td>
            </tr>
        {% endfor %}
      </tr>
    </thead>
    </table>

    <a href="{%  url 'polls:detail' question.id %}">Vote again?</a>
    <br>
    <a href="{%  url 'polls:polls' %}">Back to polls</a>


    <div id="piechart"></div>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

    <script type="text/javascript">
    // Load google charts
    google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawChart);


    // Draw the chart and set the chart values
    function drawChart() {
        var temp_data = []
        var table = document.getElementById("choice_table");
        for (var i = 1, row; row = table.rows[i]; i++) {
            temp = []
            for (var j = 0, col; col = row.cells[j]; j++) {
                var val
                if(j==1 && i!=0){
                    val = col.innerHTML
                    val = val.charAt(0)
                    val = parseInt(val)
                }else{
                    val=col.innerHTML
                }
                temp.push(val)
            }
            temp_data.push(temp)

        }
        var google_data = new google.visualization.DataTable();
        google_data.addColumn('string', 'Choice');
        google_data.addColumn('number', 'Answers')
        for (var i = 0; i < temp_data.length; i++){
            google_data.addRow([temp_data[i][0], temp_data[i][1]])
        }
        console.log(temp_data)

        // Optional; add a title and set the width and height of the chart
        var options = {'width': 550, 'height': 400};

        // Display the chart inside the <div> element with id="piechart"
        var chart = new google.visualization.PieChart(document.getElementById('piechart'));
        chart.draw(google_data, options);
    }
    </script>
</body>
</html>